services:
  db:
    environment:
      - POSTGRES_PASSWORD=caluma
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"
  caluma:
    image: ghcr.io/projectcaluma/caluma:dev
    build:
      context: .
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    # example for profiling
    # command: ./manage.py runprofileserver --use-cprofile 0.0.0.0:8000 --nothreading --prof-path /app
    environment:
      - ENV=development
      # The MINIO storage configuration doesn't imply that we need to use
      # MinIO: We currently use Garage, but due to backwards-compatibility, the
      # settigns ar still named MINIO_*
      - MINIO_STORAGE_ENDPOINT=garage:3900
      - MINIO_STORAGE_ACCESS_KEY=s3storageadmin
      - MINIO_STORAGE_SECRET_KEY=s3storageSecret
      - MINIO_STORAGE_REGION_NAME=garage
  garage:
    image: dxflrs/garage:v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900"
    environment:
      - GARAGE_DEFAULT_ACCESS_KEY=s3storageadmin
      - GARAGE_DEFAULT_SECRET_KEY=s3storageSecret
      - GARAGE_DEFAULT_BUCKET=caluma-media
    command: /garage server --single-node --default-bucket
volumes:
  garage_meta:
  garage_data:
