services:
  db:
    environment:
      - POSTGRES_PASSWORD=caluma
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"
  caluma:
    image: ghcr.io/projectcaluma/caluma:dev
    build:
      context: .
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    # example for profiling
    # command: ./manage.py runprofileserver --use-cprofile 0.0.0.0:8000 --nothreading --prof-path /app
    environment:
      - ENV=development
  minio:
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z@sha256:7d9c041cf592851fc42b970dc1e56f49fe0600c658e75833825ac1c75ec0e9da
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server data
