# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 12:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        )
    ]
