# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
