# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("form", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_hidden",
            field=models.TextField(default="false"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_required",
            field=models.TextField(default="false"),
        ),
    ]
