# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("form", "0002_auto_20181009_0753")]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="answer", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="document", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="document", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="form", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="form", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="formquestion", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="formquestion", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="option", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="option", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="question", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="question", old_name="modified", new_name="modified_at"
        ),
        migrations.RenameField(
            model_name="questionoption", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="questionoption", old_name="modified", new_name="modified_at"
        ),
        migrations.AddField(
            model_name="answer",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="formquestion",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="formquestion",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="created_by_group",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="created_by_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
