# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [("form", "0002_auto_20180910_1400")]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "label",
                    localized_fields.fields.field.LocalizedField(required=["en"]),
                ),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="form.Question",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
