# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [("form", "0012_auto_20190416_1835")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="static_content",
            field=localized_fields.fields.field.LocalizedField(
                blank=True, null=True, required=[]
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "multiple_choice"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("date", "date"),
                    ("choice", "choice"),
                    ("textarea", "textarea"),
                    ("text", "text"),
                    ("table", "table"),
                    ("form", "form"),
                    ("file", "file"),
                    ("static", "static"),
                ],
                max_length=15,
            ),
        ),
    ]
