# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("form", "0017_auto_20190619_1320")]

    operations = [migrations.RemoveField(model_name="answer", name="value_document")]
