# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 05:40
from __future__ import unicode_literals

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def attach_form_sub_answers_to_main_document(apps, schema_editor):
    """Answers to sub-questions of FormQuestions share document with parent."""
    Answer = apps.get_model("form", "Answer")
    for a in Answer.objects.filter(question__type="form"):
        if a.value_document:
            for answer in a.value_document.answers.all():
                answer.document = a.document
                answer.save()
            a.value_document.delete()
        a.delete()


def undo_attach_form_sub_answers_to_main_document(apps, schema_editor):
    """Provide a dummy for reverting migrations."""
    logger.warning(
        "Reverting '0018_remove_answer_value_document_data_migration'"
        "doesn't nest the answer structure."
    )


class Migration(migrations.Migration):

    dependencies = [("form", "0017_auto_20190619_1320")]

    operations = [
        migrations.RunPython(
            attach_form_sub_answers_to_main_document,
            undo_attach_form_sub_answers_to_main_document,
        )
    ]
