# Generated by Django 2.2.3 on 2019-07-11 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("form", "0021_auto_20190708_0905")]

    operations = [
        migrations.RemoveField(model_name="question", name="options"),
        migrations.AddField(
            model_name="historicalquestion",
            name="option_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="option_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list, size=None
            ),
        ),
    ]
