# Generated by Django 2.2.3 on 2019-07-11 12:51

import logging

from django.db import migrations

from caluma.form import models

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [("form", "0022_auto_20190711_1039")]

    def revert_migrate_option_slugs(apps, schema_editor):
        logger.warning(
            "Reverting '0023_option_slugs' won't work and QuestionOptions are lost."
        )

    def migrate_option_slugs(apps, schema_editor):
        QuestionOption = apps.get_model("form", "QuestionOption")
        Question = apps.get_model("form", "Question")

        questions = Question.objects.filter(
            type__in=[models.Question.TYPE_MULTIPLE_CHOICE, models.Question.TYPE_CHOICE]
        )

        for question in questions:
            question.option_slugs = list(
                QuestionOption.objects.filter(question=question).values_list(
                    "option", flat=True
                )
            )
            question.save()

    operations = [
        migrations.RunPython(migrate_option_slugs, revert_migrate_option_slugs)
    ]
