# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 12:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("next", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TaskSpecification",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", localized_fields.fields.field.LocalizedField(required=["en"])),
                (
                    "description",
                    localized_fields.fields.field.LocalizedField(blank=True, null=True),
                ),
                (
                    "type",
                    models.CharField(choices=[("simple", "simple")], max_length=50),
                ),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="WorkflowSpecification",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", localized_fields.fields.field.LocalizedField(required=["en"])),
                (
                    "description",
                    localized_fields.fields.field.LocalizedField(blank=True, null=True),
                ),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ("is_published", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="workflow.TaskSpecification",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="flow",
            name="task_specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="workflow.TaskSpecification",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="workflow_specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="workflow.WorkflowSpecification",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flow",
            unique_together=set([("workflow_specification", "task_specification")]),
        ),
    ]
