# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workflow", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="taskspecification",
            name="type",
            field=models.CharField(
                choices=[("simple", "Task which can only be marked as completed.")],
                max_length=50,
            ),
        )
    ]
