# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("form", "0002_auto_20181009_0753"), ("workflow", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cases",
                to="form.Document",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="workflows",
                to="form.Form",
            ),
        ),
    ]
