# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("form", "0001_initial"), ("workflow", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="workflows",
                to="form.Form",
            ),
        ),
        migrations.AddField(
            model_name="workflowspecification",
            name="form_specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="form.FormSpecification",
            ),
        ),
    ]
