# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("workflow", "0002_auto_20180913_1331")]

    operations = [
        migrations.AlterField(
            model_name="workflowspecification",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="workflow.TaskSpecification",
            ),
        )
    ]
