# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 13:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("workflow", "0003_auto_20180919_0718")]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("maybe", "Task might run in the future."),
                            ("ready", "Task is ready to be processed."),
                            ("complete", "Task is done."),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                (
                    "task_specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tasks",
                        to="workflow.TaskSpecification",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "running",
                                "Workflow is running and tasks need to be completed.",
                            ),
                            ("complete", "Workflow is done."),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("meta", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                (
                    "workflow_specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="workflows",
                        to="workflow.WorkflowSpecification",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="task",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="workflow.Workflow",
            ),
        ),
    ]
