# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("workflow", "0004_auto_20181205_1222")]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="child_case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_work_item",
                to="workflow.Case",
            ),
        )
    ]
