# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("workflow", "0005_workitem_child_case")]

    operations = [
        migrations.CreateModel(
            name="TaskFlow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "created_by_group",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(name="flow", unique_together=set([])),
        migrations.AddField(
            model_name="taskflow",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_flows",
                to="workflow.Flow",
            ),
        ),
        migrations.AddField(
            model_name="taskflow",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_flows",
                to="workflow.Task",
            ),
        ),
        migrations.AddField(
            model_name="taskflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_flows",
                to="workflow.Workflow",
            ),
        ),
        migrations.RemoveField(model_name="flow", name="task"),
        migrations.RemoveField(model_name="flow", name="workflow"),
        migrations.AlterUniqueTogether(
            name="taskflow", unique_together=set([("workflow", "task")])
        ),
    ]
