# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 15:24
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [("workflow", "0006_auto_20181207_1512")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=localized_fields.fields.field.LocalizedField(required=[]),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=localized_fields.fields.field.LocalizedField(required=[]),
        ),
    ]
