# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workflow", "0010_auto_20190213_1050")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_multiple_instance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("simple", "Task which can simply be marked as completed."),
                    (
                        "complete_workflow_form",
                        "Task to complete a defined workflow form.",
                    ),
                    ("complete_task_form", "Task to complete a defined task form."),
                ],
                max_length=50,
            ),
        ),
    ]
