# Generated by Django 2.2.8 on 2020-01-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("caluma_form", "0027_auto_20200113_0727")]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference this document has been copied from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="caluma_form.Document",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Reference this document has been copied from",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="caluma_form.Document",
            ),
        ),
    ]
