# Generated by Django 2.2.10 on 2020-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("caluma_form", "0029_dynamic_option_unique_together")]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalform",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name="historicaloption",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name="option",
            name="slug",
            field=models.SlugField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
