# Generated by Django 2.2.12 on 2020-06-19 14:21

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


def add_initial_historical_question_type(apps, schema_editor):
    HistoricalAnswer = apps.get_model("caluma_form", "HistoricalAnswer")
    HistoricalQuestion = apps.get_model("caluma_form", "HistoricalQuestion")

    for answer in HistoricalAnswer.objects.all():
        try:
            question = (
                HistoricalQuestion.objects.filter(
                    slug=answer.question_id, history_date__lte=answer.history_date
                )
                .order_by("-history_date")
                .latest()
            )
        except ObjectDoesNotExist:
            # historical question not found, falling back to current question
            question = answer.question
        answer.history_question_type = question.type
        answer.save()


class Migration(migrations.Migration):

    dependencies = [("caluma_form", "0034_fix_fk_lengths")]

    operations = [
        migrations.AddField(
            model_name="historicalanswer",
            name="history_question_type",
            field=models.CharField(default="text", max_length=23),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_initial_historical_question_type, migrations.RunPython.noop
        ),
    ]
