# Generated by Django 2.2.22 on 2021-09-29 16:48

from django.db import migrations


def add_path_attribute(apps, schema_editor):
    for doc in apps.get_model("caluma_form.document").objects.all():
        doc.path = doc.calculate_path()
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("caluma_form", "0041_add_path_attribute"),
    ]

    operations = [migrations.RunPython(add_path_attribute, migrations.RunPython.noop)]
