# Generated by Django 3.2.19 on 2023-07-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caluma_form", "0046_file_answer_reverse_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
