# Generated by Django 4.2.16 on 2024-10-16 09:40

import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caluma_form", "0048_option_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.UUIDField(
                default=uuid_extensions.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="answerdocument",
            name="id",
            field=models.UUIDField(
                default=uuid_extensions.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                default=uuid_extensions.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="dynamicoption",
            name="id",
            field=models.UUIDField(
                default=uuid_extensions.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=models.UUIDField(
                default=uuid_extensions.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid_extensions.uuid7, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswerdocument",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid_extensions.uuid7, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid_extensions.uuid7, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicaldynamicoption",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid_extensions.uuid7, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid_extensions.uuid7, editable=False
            ),
        ),
    ]
