# Generated by Django 3.2.12 on 2022-03-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caluma_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsfield",
            name="function",
            field=models.CharField(
                choices=[
                    ("group", "Group by"),
                    ("sum", "Sum"),
                    ("avg", "Average"),
                    ("max", "Max"),
                    ("min", "Min"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticstable",
            name="base_table",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="following_analytics_tables",
                to="caluma_analytics.analyticstable",
            ),
        ),
        migrations.AddField(
            model_name="analyticstable",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("type_extraction", "Data extraction"),
                    ("type_pivot", "Pivot table"),
                ],
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalanalyticsfield",
            name="function",
            field=models.CharField(
                choices=[
                    ("group", "Group by"),
                    ("sum", "Sum"),
                    ("avg", "Average"),
                    ("max", "Max"),
                    ("min", "Min"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalanalyticstable",
            name="base_table",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="caluma_analytics.analyticstable",
            ),
        ),
        migrations.AddField(
            model_name="historicalanalyticstable",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("type_extraction", "Data extraction"),
                    ("type_pivot", "Pivot table"),
                ],
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="analyticstable",
            name="starting_object",
            field=models.CharField(
                choices=[("cases", "Cases")], max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalyticstable",
            name="starting_object",
            field=models.CharField(
                choices=[("cases", "Cases")], max_length=250, null=True
            ),
        ),
    ]
