# Generated by Django 2.2.22 on 2021-09-29 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caluma_workflow", "0027_add_modified_by_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                default=list,
                help_text="Stores a path to the given object",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                default=list,
                help_text="Stores a path to the given object",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalworkitem",
            name="path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                default=list,
                help_text="Stores a path to the given object",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                default=list,
                help_text="Stores a path to the given object",
                size=None,
            ),
        ),
    ]
