# Generated by Django 2.2.22 on 2021-09-29 15:20

from django.db import migrations


def add_path_attribute(apps, schema_editor):
    for model in [
        "caluma_workflow.workitem",
        "caluma_workflow.case",
    ]:
        for obj in apps.get_model(model).objects.all():
            obj.path = obj.calculate_path()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("caluma_workflow", "0028_add_path_attribute"),
    ]

    operations = [migrations.RunPython(add_path_attribute, migrations.RunPython.noop)]
