# Generated by Django 2.2.22 on 2021-09-29 15:20

from django.db import migrations

from caluma.caluma_core.models import PathModelMixin
from caluma.caluma_workflow.models import Case, WorkItem


def add_path_attribute(apps, schema_editor):
    for model, cls in [
        ("caluma_workflow.workitem", WorkItem),
        ("caluma_workflow.case", Case),
    ]:
        for obj in apps.get_model(model).objects.all():

            obj.path = PathModelMixin.calculate_path(
                obj, path_parent_attrs=cls.path_parent_attrs
            )
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("caluma_workflow", "0028_add_path_attribute"),
    ]

    operations = [migrations.RunPython(add_path_attribute, migrations.RunPython.noop)]
