strict = set(
    """
caluma/caluma_core/tests/test_mutation.py::test_invalid_mutation_update_mutate_and_get_payload
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_without_permission
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_without_object_permission
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_permission_classes_improperly_configured
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_validation_classes_improperly_configured
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_update_not_allowed
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_create_not_allowed
caluma/caluma_core/tests/test_mutation_params.py::test_get_mutation_params_inline
caluma/caluma_core/tests/test_mutation_params.py::test_get_mutation_params_with_vars
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_for_custom_node
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_with_multiple_mutations
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_object_permission_with_multiple_mutations
caluma/caluma_data_source/tests/test_data_source.py::test_data_sources_stores_user[dynamic_choice-MyDataSource]
caluma/caluma_form/tests/test_document.py::test_query_all_documents[integer-None-1-None]
caluma/caluma_form/tests/test_document.py::test_query_all_documents[float-None-2.1-None]
caluma/caluma_form/tests/test_document.py::test_complex_document_query_performance
caluma/caluma_form/tests/test_document.py::test_save_document[True]
caluma/caluma_form/tests/test_document.py::test_save_document_table_answer_setting_family[table]
caluma/caluma_form/tests/test_document.py::test_validity_query[true-text-None-False]
caluma/caluma_form/tests/test_document.py::test_validity_query[false-text-None-True]
caluma/caluma_form/tests/test_document.py::test_validity_query[true-text-None-True]
caluma/caluma_form/tests/test_document.py::test_validity_with_visibility[True]
caluma/caluma_form/tests/test_document.py::test_validity_with_visibility[False]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-matching-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[multiple_choice-search_value0-nomatch-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-matching-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-nomatch-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[integer-10-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-matching-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-matching-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-matching-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-matching-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-nomatch-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-nomatch-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-nomatch-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[text-foo-nomatch-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-matching-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-matching-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-matching-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-matching-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-nomatch-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-nomatch-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-nomatch-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[textarea-foo-nomatch-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-matching-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-nomatch-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[float-11.5-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-None]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-EXACT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-ISNULL]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-matching-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-None]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-EXACT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-ISNULL]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[datetime-2018-05-09T14:54:51.728786-nomatch-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-matching-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-matching-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-nomatch-CONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[date-2018-05-09-nomatch-INTERSECTS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-matching-LT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-STARTSWITH]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-ICONTAINS]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-GTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-GT]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-LTE]
caluma/caluma_form/tests/test_filter_by_answer.py::test_query_all_questions[choice-a-nomatch-LT]
caluma/caluma_form/tests/test_form.py::test_query_all_forms[First result-1st-float]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators0-some text-False-text]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators0-some text-False-textarea]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators2-some text-False-text]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators2-some text-False-textarea]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators4-+411234567890-False-text]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators4-+411234567890-False-textarea]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators5-test@example.com-False-text]
caluma/caluma_form/tests/test_format_validators.py::test_base_format_validators[question__format_validators5-test@example.com-False-textarea]
caluma/caluma_form/tests/test_history.py::test_historical_file_answer
caluma/caluma_form/tests/test_history.py::test_historical_table_answer
caluma/caluma_form/tests/test_question.py::test_query_all_questions[integer-question__configuration0-None-question__format_validators0]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[float-question__configuration1-None-question__format_validators1]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[float-question__configuration2-None-question__format_validators2]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[date-question__configuration3-None-question__format_validators3]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[text-question__configuration4-None-question__format_validators4]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[textarea-question__configuration5-None-question__format_validators5]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[choice-question__configuration6-None-question__format_validators6]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[multiple_choice-question__configuration7-None-question__format_validators7]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[form-question__configuration8-None-question__format_validators8]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[file-question__configuration9-None-question__format_validators9]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[dynamic_choice-question__configuration10-MyDataSource-question__format_validators10]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[dynamic_multiple_choice-question__configuration11-MyDataSource-question__format_validators11]
caluma/caluma_form/tests/test_question.py::test_query_all_questions[static-question__configuration12-None-question__format_validators12]
caluma/caluma_form/tests/test_question.py::test_save_text_question[text-question__configuration0-question__format_validators0-True]
caluma/caluma_form/tests/test_question.py::test_save_text_question[text-question__configuration1-question__format_validators1-True]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_choice_question[dynamic_choice-True]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_choice_question[dynamic_choice-False]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_choice_question[dynamic_multiple_choice-True]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_choice_question[dynamic_multiple_choice-False]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_multiple_choice_question[dynamic_multiple_choice-True]
caluma/caluma_form/tests/test_question.py::test_save_dynamic_multiple_choice_question[dynamic_multiple_choice-False]
caluma/caluma_form/tests/test_search_answers.py::test_search_invalid_question_type
caluma/caluma_user/tests/test_permissions.py::test_is_authenticated_permission[admin_info-True]
caluma/caluma_user/tests/test_visibility.py::test_authenticated_visibility[admin_info-1]
caluma/caluma_workflow/tests/test_case.py::test_start_case[saveCase-["group-name"]|groups-100]
caluma/caluma_workflow/tests/test_case.py::test_start_case[saveCase-["group-name"]|groups-None]
caluma/caluma_workflow/tests/test_case.py::test_start_case[saveCase-None-100]
caluma/caluma_workflow/tests/test_case.py::test_start_case[saveCase-None-None]
caluma/caluma_workflow/tests/test_case.py::test_cancel_case[running-True-completed]
caluma/caluma_workflow/tests/test_case.py::test_cancel_case[running-True-ready]
caluma/caluma_workflow/tests/test_task.py::test_query_all_tasks[simple]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_last[ready-completed-True-simple-None]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_workflow_form_work_item[ready-None-running-complete_workflow_form-float-1.0-True]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_task_form_work_item[integer-1-True-ready-None-running-complete_task_form-None]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_multiple_instance_task_form_work_item[integer-1]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_multiple_instance_task_form_work_item_next[integer-1]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[["some-group"]|groups-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[info.prev_work_item.controlling_groups-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[info.work_item.created_by_group-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[info.case.created_by_group-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[[info.case.created_by_group, info.work_item.created_by_group]|groups-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next[[info.case.created_by_group, info.work_item.created_by_group]-ready-None-simple-work_item__controlling_groups0-work-item-creating-group-case-creating-group]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next_multiple_tasks[ready-None-simple]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_next_multiple_instance_task[ready-None-simple]
caluma/caluma_workflow/tests/test_work_item.py::test_complete_work_item_with_merge[completed-None-simple]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-False-None-None-ready-False-False]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-None-None-completed-False-False]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-["groups-transform"]|groups-expected_groups2-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-info.case.created_by_group-expected_groups3-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-info.work_item.created_by_group-expected_groups4-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True--expected_groups5-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-None-expected_groups6-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-info.prev_work_item.controlling_groups-expected_groups7-ready-False-True]
caluma/caluma_workflow/tests/test_work_item.py::test_create_work_item[Task name-Task description-None-group-case-True-info.work_item.created_by_group-expected_groups8-ready-True-True]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_task_form_work_item[integer-1-ready-None-running-complete_task_form-None]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_task_form_work_item[choice--ready-None-running-complete_task_form-None]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_multiple_instance_task_form_work_item[integer-1-completed-False]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_multiple_instance_task_form_work_item[integer-1-canceled-False]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_multiple_instance_task_form_work_item[integer-1-skipped-False]
caluma/caluma_workflow/tests/test_work_item.py::test_skip_multiple_instance_task_form_work_item[integer-1-ready-True]
caluma/caluma_workflow/tests/test_workflow.py::test_query_all_workflows
caluma/caluma_data_source/tests/test_data_source.py::test_fetch_data_sources
caluma/caluma_data_source/tests/test_data_source.py::test_fetch_data_from_data_source
caluma/caluma_data_source/tests/test_data_source.py::test_data_source_defaults
caluma/caluma_form/tests/test_format_validators.py::test_fetch_format_validators
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_validation_classes_custom_validation
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_object_permission_with_duplicates
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_validate_custom_node
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_validate_no_class_match
caluma/caluma_form/tests/test_history.py::test_document_as_of
caluma/caluma_form/tests/test_option.py::test_dynamic_option
caluma/caluma_workflow/tests/test_case.py::test_root_case_filter
caluma/caluma_workflow/tests/test_events.py::test_events
caluma/tests/test_schema.py::test_schema_introspect
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_not_allowed
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_with_duplicates
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_created_by_group
""".strip().splitlines()
)

non_strict = set(
    """
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_not_allowed
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_without_permission
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_without_object_permission
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_object_permission_with_duplicates
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_create_not_allowed
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_validate_custom_node
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_permission_classes_improperly_configured
caluma/caluma_core/tests/test_mutation.py::test_user_defined_primary_key_get_serializer_kwargs_update_not_allowed
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_for_custom_node
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_with_duplicates
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_permission_with_multiple_mutations
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_created_by_group
caluma/caluma_core/tests/test_mutation.py::test_invalid_mutation_update_mutate_and_get_payload
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_validation_classes_improperly_configured
caluma/caluma_core/tests/test_mutation.py::test_mutation_mutate_and_get_payload_validation_classes_custom_validation
caluma/caluma_core/tests/test_permissions.py::test_custom_permission_override_has_object_permission_with_multiple_mutations
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_validate_no_class_match
caluma/caluma_user/tests/test_permissions.py::test_is_authenticated_permission[admin_info-True]
caluma/caluma_user/tests/test_visibility.py::test_authenticated_visibility[admin_info-1]
caluma/caluma_core/tests/test_validations.py::test_custom_validation_override_validate_with_duplicates
""".strip().splitlines()
)
